version: '3'
services:
#  flask:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - ENV=production
#      - PORT=8000
#      - DOCKER=docker
#      - POSTGRES_HOST=postgres
#      - POSTGRES_PORT=5432
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=template123
#    ports:
#      - 80:8000

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=template123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
